import { LineEdit, Button, Slider, HorizontalBox, VerticalBox, ProgressIndicator, StandardTableView, GroupBox } from "std-widgets.slint";
// This code offers a datastructure and callback for the table view page
// note: this code is taken from one of the examples in the documentation, https://docs.slint.dev/latest/demos/gallery/
export global TableViewPageAdapter  {
    in-out property <int> name; in-out property <[[StandardListViewItem]]> row_data: [];
    pure callback filter_sort_model([[StandardListViewItem]], string, int, bool) -> [[StandardListViewItem]];
}

export component TableViewPage inherits Window {
    in-out property <duration> total-time: slider.value * 1s;
    in-out property <duration> elapsed-time;
    private property <bool> timer-running: false;
    property <int> sort-index: -1;
    property <bool> sort-acending;
    in-out property <int> name; 
    in-out property <string> current-initiative: "";
    in-out property <string> current-name: "";
    in-out property <string> current-ac: "";
    in-out property <string> current-hp: "";
    callback add-row();

    // Start of the UI definition for our table
    title: @tr("TableView");
    HorizontalBox {
        vertical-stretch: 1;
        // Create a box to store table, filter, and buttons
        GroupBox {
            title: @tr("StandardTableView");
            vertical-stretch: 0;

            VerticalLayout {
                
                StandardTableView {
                    // account for both ascending and descending sorting
                    sort-descending(index) => {
                        root.sort-index = index;
                        root.sort-acending = false;
                    }
                    // create the columns for the table
                    columns: [
                        { 
                        title: @tr("Initiative")     
                        },
                        { title: @tr("Name") },
                        { title: @tr("AC") },
                        { title: @tr("HP") },
                    ];
                    // create the rows for the table dynamically, based on the row_data property and the filter_sort_model callback
                    // note: this code is taken from one of the examples in the documentation, https://docs.slint.dev/latest/demos/gallery/
                    rows: TableViewPageAdapter.filter_sort_model(TableViewPageAdapter.row_data, filter-edit.text, root.sort-index, root.sort-acending);
                }

                VerticalLayout {
                    // create a filter for the table
                    Text {
                        text: @tr("Filter by Header 2:");
                    }
                    filter-edit := LineEdit {
                        placeholder-text: @tr("Enter filter text");
                    }
                }   
                // create inputs for the user to add new rows to the table
                HorizontalBox {
                    LineEdit {
                        font-size: 14px;
                        placeholder-text: "Enter initiative";
                        text <=> root.current-initiative;

                    }
                    LineEdit {
                        font-size: 14px;
                        placeholder-text: "Enter Name";
                        text <=> root.current-name;
                    }
                    LineEdit {
                        font-size: 14px;
                        placeholder-text: "Enter AC";
                        text <=> root.current-ac;
                    }
                    LineEdit {
                        font-size: 14px;
                        placeholder-text: "Enter HP";
                        text <=> root.current-hp;
                    }
                    Button {
                        text: @tr("Add Row");
                        clicked => {
                            root.add-row();
                            root.current-initiative = "";
                            root.current-ac = "";
                            root.current-hp = "";
                            root.current-name = "";
                        }
                    }
                    Button {
                        text: @tr("Sort by Initiative");
                        clicked => {
                            root.sort-index = 0;
                            root.sort-acending = false;
                        }
                    }
                }
            }
        }
        VerticalBox {
            Timer {
                interval: 10ms;
                running: root.timer-running;
                triggered => {
                    root.elapsed-time += self.interval;
                    root.elapsed-time = min(root.elapsed-time, root.total-time);
                }
            }
            HorizontalBox {
                padding: 0;
                Text { 
                    text: "Elapsed Time:"; 
                }
                ProgressIndicator {
                    preferred-width: 100px;
                    progress: elapsed-time / total-time;
                }
            }
            Text{
                text: "Elapsed time: " + (root.elapsed-time / 1s) + "s";
            }
            Text{
                text: "total time: " + (root.total-time / 1s) + "s";
            }
            HorizontalBox {
                padding: 0;
                Text {
                    text: "Duration:";
                    vertical-alignment: center;
                }
                slider := Slider {
                    maximum: 9.22882; // Log 2 scale
                    value: 60; // default time
                      
                    changed(new-log-value) => {
                        root.total-time = pow(2, new-log-value) * 1s;
                        root.elapsed-time = min(root.elapsed-time, root.total-time);
                    }
                }
            }
            HorizontalBox {
                spacing: 10px;
                Button {
                    text: "Start";
                    clicked => {
                        root.timer-running = true;
                    }
                }
                Button {
                    text: "Stop";
                    clicked => {
                        root.timer-running = false;
                    }
                }
                Button {
                    text: "Reset";
                    clicked => {
                        root.timer-running = false;
                        root.elapsed-time = 0;
                    }
                }
            }
        }
    }

}
        
        

